import requests
from bs4 import BeautifulSoup
import os
from time import sleep
import string

print("Dictionaree v0.1.17")
print("Copyright (c) 2021 Qizhen Yang")
print("Dictionaree is a FREE software.")
print(" *  GitHub repo: Qizhen-Yang/dictionaree")
print(" *  License: MIT License\n")
print("Type any word you want to search below. Type `eof` to end.")
print("Using dictionary: Youdao Dictionary (en <-> zh_cn)\n")

i = []
a = input("Add a word $ ")
i.append(a)
while a.lower() != "eof":
	a = input("Add a word $ ")
	i.append(a)
i.pop()
print("End of inputting.\n")

if i == []:
	print("Nothing to show. XD")
else:
	header = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36", 
			 "Cookie": "your cookie"}
	d = []
	for word in i:
		result = requests.get("http://youdao.com/w/eng/" + word, headers=header)
		result_bs = BeautifulSoup(result.text, "html.parser")
		newitem = str(result_bs.find("h2", attrs = {'class': 'wordbook-js'}))
		if newitem == "None":
			d.append([word, "<br/><br/> No definitions"])
			print("Failed to find definition of:", word)
		else:
			newitem += str(result_bs.find("div", attrs = {'class': 'trans-container'}))
			newitem = newitem.replace("<ul>", "<div>")
			newitem = newitem.replace("</ul>", "</div>")
			newitem = newitem.replace("<li>", "<p>")
			newitem = newitem.replace("</li>", "</p>")
			newitem = newitem.replace("<a", "<span")
			newitem = newitem.replace("</a>", "</span>")
			d.append(newitem)
			print("Added word:", word)

	f = open("Dictionaree.html", "w+", encoding = "utf-8")
	f.write("<meta charset='utf-8'/>")
	f.write("<style>*{font-size:16px;}.word{margin:auto;width:fit-content;text-align:center;}.baav{font-weight:400;margin-top:16px;}html{margin:auto;max-width:21cm;}hr{width:50%;}.additional,.more-example,.collapse-content,.wt-collapse,#webPhrase,.sp{display:none;}.keyword{display:block'}</style>")
	for word_def in d:
		f.write("<div class='word'>")
		for j in word_def:
			f.write(str(j))
		f.write("</div><hr/>")
	f.write("<center>Generated by <a href='https://github.com/Qizhen-Yang/dictionaree'>Dictionaree</a>, a great work by Qizhen Yang.</center>")
	f.close()
	print("Generated file: Dictionaree.html")
	os.startfile("Dictionaree.html")
	sleep(5)
	os.remove("Dictionaree.html")