import requests
from bs4 import BeautifulSoup
import os
from time import sleep
import string

import youdao
import collins

clear = os.system("cls")

print("Dictionaree v0.2.2")
print("Copyright (c) 2021 Qizhen Yang")
print("Dictionaree is a FREE software.")
print(" *  GitHub repo: Qizhen-Yang/dictionaree")
print(" *  License: MIT License\n")

print("Using dictionaries: Youdao (en <-> zh_cn) and Collins (en <-> en)")

print("\nType any word you want to search below. Type `eof` to end.\n")

i = []
d = []
a = input("Add a word $ ")
i.append(a)
while a.lower() != "eof":
	a = input("Add a word $ ")
	i.append(a)
i.pop()
print("End of inputting.\n")

if i == []:
	print("Nothing to show. XD")
else:
	for word in i:
		d.append(["[Youdao]", youdao.search(word), "[Collins]", collins.search(word)])

	f = open("Dictionaree.html", "w+", encoding = "utf-8")
	f.write("<meta charset='utf-8'/>")
	f.write("<style>*{font-size:16px;}.word{margin:auto;width:fit-content;text-align:center;}.baav,.hom,.content{font-weight:400;margin-top:16px;}html{margin:auto;max-width:21cm;}hr{width:50%;}.additional,.more-example,.collapse-content,.wt-collapse,#webPhrase,.sp,.sensenum,.cit,.xr,.title_frequency_container,.copyright,.entry_title,.thes{display:none;}.keyword{display:block;}.pos,.type-gram{text-transform:uppercase;},.orth{font-weight:bold;}</style>")
	for word_def in d:
		f.write("<div class='word'>")
		for item in word_def:
			for item_ in item:
				f.write(str(item_))
		f.write("</div><hr/>")
	f.write("<center>Generated by <a href='https://github.com/Qizhen-Yang/dictionaree'>Dictionaree</a>, a great work by Qizhen Yang.</center>")
	f.close()
	print("Generated file: Dictionaree.html")
	os.startfile("Dictionaree.html")